flags: {}
packages:
- 'hslua'
- 'hslua-aeson'
- 'hslua-cli'
- 'hslua-core'
- 'hslua-classes'
- 'hslua-list'
- 'hslua-marshalling'
- 'hslua-module-path'
- 'hslua-module-system'
- 'hslua-module-text'
- 'hslua-module-version'
- 'hslua-objectorientation'
- 'hslua-packaging'
- 'hslua-typing'
- 'lua'
- 'lua-arbitrary'
- 'tasty-lua'
- 'tasty-hslua'
resolver: 'lts-20.14'
